#!/usr/bin/env python3

# https://github.com/zzag/plasma5-wallpapers-dynamic/wiki/metadata.json-keys
# Ouput a real number between 0 and 1, which is computed as follows
# time = the number of seconds since the start of the day / 86400
#
# $ ./convert-time.py "10:44 AM"
# 0.44722222222222224
#
# $ ./convert-time.py "10:44"
# 0.44722222222222224
#
# $ ./convert-time.py "10:44 PM"
# 0.9472222222222222
#
# $ ./convert-time.py "22:44"
# 0.9472222222222222

import argparse

from dateutil import parser as datetime_parser

argument_parser = argparse.ArgumentParser()
argument_parser.add_argument('input')
arguments = argument_parser.parse_args()

datetime = datetime_parser.parse(arguments.input)
midnight = datetime.replace(hour=0, minute=0, second=0, microsecond=0)

print((datetime - midnight).total_seconds() / 86400)